/**
 * @license
 * Copyright 2025 AionUi (aionui.com)
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Source-derived registry of provider keys that the Electron renderer may invoke.
 *
 * Generated from literal `bridge.buildProvider(...)` call sites under
 * `packages/desktop/src/common` and `packages/desktop/src/renderer`.
 * The R4 freshness test fails whenever either source surface and this exact list
 * diverge. Do not replace this registry with a prefix, glob, or runtime
 * "provider exists" fallback.
 */
export const RENDERER_PROVIDER_KEYS = [
  'app.get-cdp-status',
  'app.get-browser-context',
  'app.get-gpu-status',
  'app.get-path',
  'app.get-start-on-boot-status',
  'app.get-zoom-factor',
  'app.read-generated-artifact-preview',
  'app.release-browser-webcontents-lease',
  'app.report-browser-webcontents-id',
  'app.revoke-browser-context',
  'app.save-browser-workbench-state',
  'app.set-gpu-override',
  'app.set-start-on-boot',
  'app.set-zoom-factor',
  'app.update-cdp-config',
  'app.write-renderer-log',
  'auto-update.check',
  'auto-update.download',
  'auto-update.get-status',
  'auto-update.quit-and-install',
  'command-eve.active-seat',
  'command-eve.artifact-context-envelope',
  'command-eve.artifact-turn-steer',
  'command-eve.auth-logout',
  'command-eve.auth-password-login',
  'command-eve.auth-resume',
  'command-eve.auth-web-login',
  'command-eve.authored-skills',
  'command-eve.command-center-read-model',
  'command-eve.cloud-visual-policy-read',
  'command-eve.cloud-visual-policy-receipt',
  'command-eve.cloud-visual-policy-set',
  'command-eve.company-brain-list',
  'command-eve.company-brain-read',
  'command-eve.company-brain-remove',
  'command-eve.company-brain-seed',
  'command-eve.company-brain-status',
  'command-eve.company-brain-write',
  'command-eve.computer-use-install',
  'command-eve.computer-use-permissions-grant',
  'command-eve.computer-use-permissions-revoke-guide',
  'command-eve.computer-use-status',
  'command-eve.connector-catalog',
  'command-eve.connector-preflight',
  'command-eve.credits-set-spend-cap',
  'command-eve.credits-status',
  'command-eve.crm-consent-local',
  'command-eve.crm-draft-create',
  'command-eve.crm-overlay',
  'command-eve.crm-overlay-initialize',
  'command-eve.crm-stage-local',
  'command-eve.ensure-assistant',
  'command-eve.ensure-local-model-tier',
  'command-eve.entitlement-activate',
  'command-eve.entitlement-register',
  'command-eve.entitlement-reset',
  'command-eve.entitlement-status',
  'command-eve.evaluate-gate-decision',
  'command-eve.external-action-execute',
  'command-eve.external-action-resume',
  'command-eve.external-action-policy-get',
  'command-eve.external-action-policy-kill',
  'command-eve.external-action-policy-revoke',
  'command-eve.external-action-policy-set',
  'command-eve.generate-local-title',
  'command-eve.guided-auth-setup',
  'command-eve.image-capabilities',
  'command-eve.image-generate',
  'command-eve.image-model-preference-read',
  'command-eve.image-model-preference-set',
  'command-eve.kanban-acp-apply',
  'command-eve.kanban-acp-peek',
  'command-eve.kanban-acp-reject',
  'command-eve.kanban-marketing-board',
  'command-eve.kanban-marketing-card-action',
  'command-eve.kanban-marketing-card-create',
  'command-eve.kanban-marketing-card-move',
  'command-eve.kanban-marketing-dispatch-approval',
  'command-eve.kanban-marketing-dispatch-decision',
  'command-eve.kanban-marketing-dispatch-plan',
  'command-eve.kanban-marketing-draft-generate',
  'command-eve.kanban-marketing-output-approve',
  'command-eve.kanban-marketing-proof-card',
  'command-eve.kanban-marketing-worker-dispatch-request',
  'command-eve.kanban-marketing-worker-dispatcher-prepare',
  'command-eve.kanban-marketing-worker-executor-promotion',
  'command-eve.kanban-marketing-worker-observed-run',
  'command-eve.kanban-marketing-worker-start-gate',
  'command-eve.kanban-preflight',
  'command-eve.learned-skills',
  'command-eve.inference-lane-decision',
  'command-eve.seat-context',
  'command-eve.license-wire-status',
  'command-eve.local-runtime-status',
  'command-eve.managed-visual-turn-authorize',
  'command-eve.multimodal-tts',
  'command-eve.multimodal-tts-consent-get',
  'command-eve.multimodal-tts-consent-set',
  'command-eve.multimodal-tts-status',
  'command-eve.my-seats',
  'command-eve.native-kanban-board',
  'command-eve.native-kanban-task-create',
  'command-eve.native-kanban-task-update',
  'command-eve.onboarding-status',
  'command-eve.open-account-web',
  'command-eve.pdf-prepare',
  'command-eve.image-prepare',
  'command-eve.image-artifact-bind',
  'command-eve.image-artifact-import-legacy',
  'command-eve.image-artifact-preview',
  'command-eve.image-artifact-reconcile',
  'command-eve.image-artifacts-list',
  'command-eve.presentation-prepare',
  'command-eve.provider-turn-binding-record',
  'command-eve.registration-status',
  'command-eve.registration-update',
  'command-eve.report-export',
  'command-eve.report-stage-workspace',
  'command-eve.resolve-inference-provider',
  'command-eve.runtime-status',
  'command-eve.seat-usage',
  'command-eve.seed-create',
  'command-eve.seed-rename',
  'command-eve.session-digest',
  'command-eve.shell-flags',
  'command-eve.skill-content',
  'command-eve.skill-library',
  'command-eve.speech-to-text-local',
  'command-eve.startscreen-note',
  'command-eve.status-surface',
  'command-eve.switch-seat',
  'command-eve.sync-worker-launcher-state',
  'command-eve.team-manage-apply',
  'command-eve.team-manage-peek',
  'command-eve.team-manage-reject',
  'command-eve.telemetry-consent-get',
  'command-eve.telemetry-consent-set',
  'command-eve.typed-ui-action-receipt',
  'command-eve.typed-ui-provenance-attestation',
  'command-eve.video-artifact-hydrate',
  'command-eve.video-artifacts-list',
  'command-eve.video-capabilities',
  'command-eve.video-edit',
  'command-eve.video-generate',
  'command-eve.warm-local-model',
  'is-dev-tools-opened',
  'notification.show',
  'open-dev-tools',
  'project-workspace.adopt',
  'project-workspace.archive',
  'project-workspace.bindConversation',
  'project-workspace.chat-intent',
  'project-workspace.commitAssignment',
  'project-workspace.create',
  'project-workspace.ensureAfterSuccessfulTurn',
  'project-workspace.list',
  'project-workspace.listConversationArtifacts',
  'project-workspace.previewAdopt',
  'project-workspace.previewAssignment',
  'project-workspace.previewCreate',
  'project-workspace.recover',
  'project-workspace.restore',
  'project-workspace.reveal',
  'project-workspace.runtime-send',
  'project-workspace.runtime-warmup',
  'project-workspace.unbindConversation',
  'project-workspace.undo',
  'project-workspace.updateMetadata',
  'restart-app',
  'show-open',
  'show-save',
  'system-settings:get-close-to-tray',
  'system-settings:get-pet-confirm-enabled',
  'system-settings:get-pet-dnd',
  'system-settings:get-pet-enabled',
  'system-settings:get-pet-size',
  'system-settings:set-close-to-tray',
  'system-settings:set-pet-confirm-enabled',
  'system-settings:set-pet-dnd',
  'system-settings:set-pet-enabled',
  'system-settings:set-pet-size',
  'theme:request-current',
  'theme:set-active',
  'update-system-info',
  'update.check',
  'update.download',
  'webui.get-status',
  'webui.start',
  'webui.stop',
  'window-controls:close',
  'window-controls:is-maximized',
  'window-controls:maximize',
  'window-controls:minimize',
  'window-controls:unmaximize',
] as const;

export type RendererProviderKey = (typeof RENDERER_PROVIDER_KEYS)[number];

export type ProviderPayloadClass = 'void' | 'optional-record' | 'record';

/**
 * The public seat-scoped Kanban reuses four legacy "marketing" wire names.
 * These providers are customer-callable only for the literal `default` board;
 * every other board slug remains founder-only in the main-process parser.
 */
export const CUSTOMER_DEFAULT_KANBAN_PROVIDER_KEYS: ReadonlySet<RendererProviderKey> = new Set([
  'command-eve.kanban-marketing-board',
  'command-eve.kanban-marketing-card-action',
  'command-eve.kanban-marketing-card-create',
  'command-eve.kanban-marketing-card-move',
]);

/**
 * Per-provider request schema class, mechanically derived from each renderer-side
 * `buildProvider<Result, Params>` declaration and frozen by the R4 source test.
 */
export const RENDERER_PROVIDER_PAYLOAD_CLASSES = {
  'app.get-cdp-status': 'void',
  'app.get-browser-context': 'void',
  'app.get-gpu-status': 'void',
  'app.get-path': 'record',
  'app.get-start-on-boot-status': 'void',
  'app.get-zoom-factor': 'void',
  'app.read-generated-artifact-preview': 'record',
  'app.release-browser-webcontents-lease': 'record',
  'app.report-browser-webcontents-id': 'record',
  'app.revoke-browser-context': 'void',
  'app.save-browser-workbench-state': 'record',
  'app.set-gpu-override': 'record',
  'app.set-start-on-boot': 'record',
  'app.set-zoom-factor': 'record',
  'app.update-cdp-config': 'record',
  'app.write-renderer-log': 'record',
  'auto-update.check': 'record',
  'auto-update.download': 'void',
  'auto-update.get-status': 'void',
  'auto-update.quit-and-install': 'void',
  'command-eve.active-seat': 'void',
  'command-eve.artifact-context-envelope': 'record',
  // conversationId + the correction text AS DELIVERED to the runtime (trimmed by
  // the send box, not raw keystrokes). Revokes only; it can grant nothing.
  'command-eve.artifact-turn-steer': 'record',
  'command-eve.auth-logout': 'void',
  'command-eve.auth-password-login': 'record',
  'command-eve.auth-resume': 'void',
  'command-eve.auth-web-login': 'record',
  'command-eve.authored-skills': 'void',
  'command-eve.command-center-read-model': 'optional-record',
  'command-eve.cloud-visual-policy-read': 'void',
  'command-eve.cloud-visual-policy-receipt': 'record',
  'command-eve.cloud-visual-policy-set': 'record',
  'command-eve.company-brain-list': 'void',
  'command-eve.company-brain-read': 'record',
  'command-eve.company-brain-remove': 'record',
  'command-eve.company-brain-seed': 'record',
  'command-eve.company-brain-status': 'void',
  'command-eve.company-brain-write': 'record',
  // Read-only status/board calls carry no renderer payload. Install/grant are
  // also void: MAIN mints their one-shot capability only after a native dialog.
  'command-eve.computer-use-install': 'void',
  'command-eve.computer-use-permissions-grant': 'void',
  'command-eve.computer-use-permissions-revoke-guide': 'void',
  'command-eve.computer-use-status': 'void',
  'command-eve.connector-catalog': 'optional-record',
  'command-eve.connector-preflight': 'record',
  'command-eve.credits-set-spend-cap': 'record',
  'command-eve.credits-status': 'void',
  'command-eve.crm-consent-local': 'record',
  'command-eve.crm-draft-create': 'optional-record',
  'command-eve.crm-overlay': 'optional-record',
  'command-eve.crm-overlay-initialize': 'optional-record',
  'command-eve.crm-stage-local': 'record',
  'command-eve.ensure-assistant': 'void',
  'command-eve.ensure-local-model-tier': 'optional-record',
  'command-eve.entitlement-activate': 'record',
  'command-eve.entitlement-register': 'record',
  'command-eve.entitlement-reset': 'void',
  'command-eve.entitlement-status': 'void',
  'command-eve.evaluate-gate-decision': 'record',
  'command-eve.external-action-execute': 'record',
  'command-eve.external-action-resume': 'record',
  'command-eve.external-action-policy-get': 'void',
  'command-eve.external-action-policy-kill': 'record',
  'command-eve.external-action-policy-revoke': 'record',
  'command-eve.external-action-policy-set': 'record',
  'command-eve.generate-local-title': 'record',
  'command-eve.guided-auth-setup': 'record',
  // MAT-1769 — no arguments: asks MAIN for the server-owned image model
  // registry (display names + credit quotes). Read-only, non-billable.
  'command-eve.image-capabilities': 'void',
  // One explicit image turn: prompt + conversation/request identity + the
  // server-owned tier, resolution/aspect ratio and optional local references.
  'command-eve.image-generate': 'record',
  // 1.820.3 — the managed image artifact lane. conversationId + handle +
  // toolCallId (bind), conversationId (list), conversationId + artifactId
  // (preview), conversationId + expectedFileName (legacy import).
  'command-eve.image-artifact-bind': 'record',
  'command-eve.image-artifact-import-legacy': 'record',
  'command-eve.image-artifact-preview': 'record',
  'command-eve.image-artifact-reconcile': 'record',
  'command-eve.image-artifacts-list': 'record',
  // No arguments — Main resolves the active seat itself.
  'command-eve.image-model-preference-read': 'void',
  // expectedSeatId (stale-action fence only) + the chosen tier.
  'command-eve.image-model-preference-set': 'record',
  'command-eve.kanban-acp-apply': 'record',
  'command-eve.kanban-acp-peek': 'void',
  'command-eve.kanban-acp-reject': 'record',
  'command-eve.kanban-marketing-board': 'optional-record',
  'command-eve.kanban-marketing-card-action': 'record',
  'command-eve.kanban-marketing-card-create': 'record',
  'command-eve.kanban-marketing-card-move': 'record',
  'command-eve.kanban-marketing-dispatch-approval': 'record',
  'command-eve.kanban-marketing-dispatch-decision': 'record',
  'command-eve.kanban-marketing-dispatch-plan': 'record',
  'command-eve.kanban-marketing-draft-generate': 'record',
  'command-eve.kanban-marketing-output-approve': 'record',
  'command-eve.kanban-marketing-proof-card': 'optional-record',
  'command-eve.kanban-marketing-worker-dispatch-request': 'record',
  'command-eve.kanban-marketing-worker-dispatcher-prepare': 'record',
  'command-eve.kanban-marketing-worker-executor-promotion': 'record',
  'command-eve.kanban-marketing-worker-observed-run': 'record',
  'command-eve.kanban-marketing-worker-start-gate': 'record',
  'command-eve.kanban-preflight': 'optional-record',
  'command-eve.learned-skills': 'void',
  'command-eve.inference-lane-decision': 'void',
  'command-eve.seat-context': 'void',
  'command-eve.license-wire-status': 'void',
  'command-eve.local-runtime-status': 'optional-record',
  'command-eve.managed-visual-turn-authorize': 'record',
  'command-eve.multimodal-tts': 'record',
  'command-eve.multimodal-tts-consent-get': 'void',
  'command-eve.multimodal-tts-consent-set': 'record',
  'command-eve.multimodal-tts-status': 'optional-record',
  'command-eve.my-seats': 'void',
  // MAIN pins the canonical default board and active seat; the renderer can
  // neither select a DB/slug nor enter Hermes-owned lifecycle states.
  'command-eve.native-kanban-board': 'void',
  'command-eve.native-kanban-task-create': 'record',
  'command-eve.native-kanban-task-update': 'record',
  'command-eve.onboarding-status': 'void',
  'command-eve.open-account-web': 'record',
  'command-eve.pdf-prepare': 'record',
  'command-eve.image-prepare': 'record',
  'command-eve.presentation-prepare': 'record',
  'command-eve.provider-turn-binding-record': 'record',
  'command-eve.registration-status': 'void',
  'command-eve.registration-update': 'record',
  'command-eve.report-export': 'record',
  'command-eve.report-stage-workspace': 'record',
  'command-eve.resolve-inference-provider': 'record',
  'command-eve.runtime-status': 'void',
  'command-eve.seat-usage': 'record',
  'command-eve.seed-create': 'record',
  'command-eve.seed-rename': 'record',
  'command-eve.session-digest': 'record',
  'command-eve.shell-flags': 'void',
  'command-eve.skill-content': 'record',
  'command-eve.skill-library': 'optional-record',
  'command-eve.speech-to-text-local': 'record',
  'command-eve.startscreen-note': 'void',
  'command-eve.status-surface': 'optional-record',
  'command-eve.switch-seat': 'record',
  'command-eve.sync-worker-launcher-state': 'void',
  'command-eve.team-manage-apply': 'record',
  'command-eve.team-manage-peek': 'void',
  'command-eve.team-manage-reject': 'record',
  'command-eve.telemetry-consent-get': 'void',
  'command-eve.telemetry-consent-set': 'record',
  'command-eve.typed-ui-action-receipt': 'record',
  'command-eve.typed-ui-provenance-attestation': 'record',
  // conversationId only — reads MAIN's own local durable video-artifact store.
  'command-eve.video-artifact-hydrate': 'record',
  'command-eve.video-artifacts-list': 'record',
  // No arguments — asks MAIN what the seat may produce. Omitting it here left the
  // wire unpoliced and therefore unreachable, so the composer silently kept its
  // default capabilities instead of the seat's real ones.
  'command-eve.video-capabilities': 'void',
  'command-eve.video-edit': 'record',
  // Prompt, tier, duration, conversationId and an optional grant-verified image
  // PATH. Main re-reads that path and computes the base64/SHA-256 itself.
  'command-eve.video-generate': 'record',
  'command-eve.warm-local-model': 'optional-record',
  'is-dev-tools-opened': 'void',
  'notification.show': 'record',
  'open-dev-tools': 'void',
  'project-workspace.adopt': 'record',
  'project-workspace.archive': 'record',
  'project-workspace.bindConversation': 'record',
  'project-workspace.chat-intent': 'record',
  'project-workspace.commitAssignment': 'record',
  'project-workspace.create': 'record',
  'project-workspace.ensureAfterSuccessfulTurn': 'record',
  'project-workspace.list': 'void',
  'project-workspace.listConversationArtifacts': 'record',
  'project-workspace.previewAdopt': 'record',
  'project-workspace.previewAssignment': 'record',
  'project-workspace.previewCreate': 'record',
  'project-workspace.recover': 'record',
  'project-workspace.restore': 'record',
  'project-workspace.reveal': 'record',
  'project-workspace.runtime-send': 'record',
  'project-workspace.runtime-warmup': 'record',
  'project-workspace.unbindConversation': 'record',
  'project-workspace.undo': 'record',
  'project-workspace.updateMetadata': 'record',
  'restart-app': 'void',
  'show-open': 'optional-record',
  'show-save': 'optional-record',
  'system-settings:get-close-to-tray': 'void',
  'system-settings:get-pet-confirm-enabled': 'void',
  'system-settings:get-pet-dnd': 'void',
  'system-settings:get-pet-enabled': 'void',
  'system-settings:get-pet-size': 'void',
  'system-settings:set-close-to-tray': 'record',
  'system-settings:set-pet-confirm-enabled': 'record',
  'system-settings:set-pet-dnd': 'record',
  'system-settings:set-pet-enabled': 'record',
  'system-settings:set-pet-size': 'record',
  'theme:request-current': 'void',
  'theme:set-active': 'record',
  'update-system-info': 'record',
  'update.check': 'record',
  'update.download': 'record',
  'webui.get-status': 'void',
  'webui.start': 'record',
  'webui.stop': 'void',
  'window-controls:close': 'void',
  'window-controls:is-maximized': 'void',
  'window-controls:maximize': 'void',
  'window-controls:minimize': 'void',
  'window-controls:unmaximize': 'void',
} as const satisfies Record<RendererProviderKey, ProviderPayloadClass>;

/**
 * Main-process authorization boundary for surfaces hidden from customer builds.
 *
 * This set implements the binding 1.819 HG-3 decision: Command Center/run
 * internals, worker launcher/team mutations, provider preflight diagnostics,
 * and CDP/DevTools controls require the main-owned founder-build signal.
 */
export const FOUNDER_ONLY_PROVIDER_KEYS: ReadonlySet<RendererProviderKey> = new Set([
  'app.get-cdp-status',
  'app.update-cdp-config',
  'command-eve.command-center-read-model',
  'command-eve.connector-preflight',
  'command-eve.crm-consent-local',
  'command-eve.crm-draft-create',
  'command-eve.crm-overlay',
  'command-eve.crm-overlay-initialize',
  'command-eve.crm-stage-local',
  'command-eve.guided-auth-setup',
  'command-eve.kanban-marketing-dispatch-approval',
  'command-eve.kanban-marketing-dispatch-decision',
  'command-eve.kanban-marketing-dispatch-plan',
  'command-eve.kanban-marketing-draft-generate',
  'command-eve.kanban-marketing-output-approve',
  'command-eve.kanban-marketing-proof-card',
  'command-eve.kanban-marketing-worker-dispatch-request',
  'command-eve.kanban-marketing-worker-dispatcher-prepare',
  'command-eve.kanban-marketing-worker-executor-promotion',
  'command-eve.kanban-marketing-worker-observed-run',
  'command-eve.kanban-marketing-worker-start-gate',
  'command-eve.kanban-preflight',
  'command-eve.status-surface',
  'command-eve.sync-worker-launcher-state',
  'command-eve.team-manage-apply',
  'command-eve.team-manage-peek',
  'command-eve.team-manage-reject',
  'is-dev-tools-opened',
  'open-dev-tools',
]);
