#!/usr/bin/env python3
"""Render JSON book metadata as TeX-safe macro definitions."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


MACROS = {
    "book_title": "BookTitle",
    "book_subtitle": "BookSubtitle",
    "book_author": "BookAuthor",
    "book_imprint": "BookImprint",
    "book_year": "BookYear",
    "book_disclaimer": "BookDisclaimer",
    "book_dedication": "BookDedication",
    "book_epigraph": "BookEpigraph",
    "book_running_title": "BookRunningTitle",
    "book_kicker": "BookKicker",
    "book_blurb": "BookBlurb",
    "book_closing": "BookClosing",
    "author_name": "AuthorName",
    "author_bio": "AuthorBio",
    "imprint_name": "ImprintName",
    "cover_kicker": "CoverKicker",
    "cover_title": "CoverTitle",
    "cover_subtitle": "CoverSubtitle",
    "cover_author": "CoverAuthor",
    "cta_title": "CtaTitle",
    "cta_body": "CtaBody",
    "cta_label": "CtaLabel",
}

TEX_ESCAPES = {
    "\\": r"\textbackslash{}",
    "{": r"\{",
    "}": r"\}",
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
    "\n": r"\par ",
}


def escape_tex(value: str) -> str:
    return "".join(TEX_ESCAPES.get(char, char) for char in value)


def render(data: dict[str, object]) -> str:
    unknown = sorted(set(data) - set(MACROS))
    if unknown:
        raise ValueError(f"Unbekannte Metadatenfelder: {', '.join(unknown)}")

    lines = ["% Generated by tex_metadata.py; do not edit by hand."]
    for key, macro in MACROS.items():
        if key not in data:
            continue
        value = data[key]
        if not isinstance(value, str):
            raise TypeError(f"{key} muss ein String sein")
        lines.append(f"\\providecommand{{\\{macro}}}{{{escape_tex(value)}}}")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Erzeugt TeX-sichere Buchmetadaten aus JSON."
    )
    parser.add_argument("input", type=Path, help="book-metadata.json")
    parser.add_argument(
        "--output", type=Path, default=Path("book-metadata.tex")
    )
    args = parser.parse_args()

    data = json.loads(args.input.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise TypeError("Die JSON-Wurzel muss ein Objekt sein")
    args.output.write_text(render(data), encoding="utf-8")
    print(f"TeX-Metadaten gebaut: {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
